services:
  db: 
    image: postgres:12
    restart: always
    volumes:
      - ./etapa-ii/tabelas.sql:/docker-entrypoint-initdb.d/01-tabelas.sql
      - ./etapa-ii/instancias.sql:/docker-entrypoint-initdb.d/02-instancias.sql
      - ./etapa-ii/consultas.sql:/docker-entrypoint-initdb.d/03-consultas.sql
      - ./etapa-iii/gatilho.sql:/docker-entrypoint-initdb.d/04-gatilho.sql
    tmpfs:
      - /var/lib/postgresql/data # Define os dados como temporários
    environment:
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: halflinkedin
    ports:
      - "5432:5432"